/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicdashboardIndexRouteImport } from './routes/(public)/(dashboard)/index'

const publicdashboardIndexRoute = publicdashboardIndexRouteImport.update({
  id: '/(public)/(dashboard)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicdashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicdashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)/(dashboard)/': typeof publicdashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/(public)/(dashboard)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicdashboardIndexRoute: typeof publicdashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)/(dashboard)/': {
      id: '/(public)/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicdashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  publicdashboardIndexRoute: publicdashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
