/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicOrdersRouteImport } from './routes/(public)/orders'
import { Route as publicCartRouteImport } from './routes/(public)/cart'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicOrdersRoute = publicOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicCartRoute = publicCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => publicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/cart': typeof publicCartRoute
  '/orders': typeof publicOrdersRoute
  '/': typeof publicIndexRoute
}
export interface FileRoutesByTo {
  '/cart': typeof publicCartRoute
  '/orders': typeof publicOrdersRoute
  '/': typeof publicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/(public)/cart': typeof publicCartRoute
  '/(public)/orders': typeof publicOrdersRoute
  '/(public)/': typeof publicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/cart' | '/orders' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/cart' | '/orders' | '/'
  id:
    | '__root__'
    | '/(public)'
    | '/(public)/cart'
    | '/(public)/orders'
    | '/(public)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/orders': {
      id: '/(public)/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof publicOrdersRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/cart': {
      id: '/(public)/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof publicCartRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicCartRoute: typeof publicCartRoute
  publicOrdersRoute: typeof publicOrdersRoute
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicCartRoute: publicCartRoute,
  publicOrdersRoute: publicOrdersRoute,
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
